# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import weather_pb2 as weather__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in weather_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WeatherHistoryStub(object):
    """python -m grpc_tools.protoc weather.proto --proto_path=. --python_out=. --grpc_python_out=. 

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSummary = channel.unary_unary(
                '/WeatherHistory/GetSummary',
                request_serializer=weather__pb2.Summary.SerializeToString,
                response_deserializer=weather__pb2.SummaryReturn.FromString,
                _registered_method=True)
        self.PrecipAnalysis = channel.unary_unary(
                '/WeatherHistory/PrecipAnalysis',
                request_serializer=weather__pb2.AnalysisSummary.SerializeToString,
                response_deserializer=weather__pb2.AnalysisReturn.FromString,
                _registered_method=True)
        self.GetPrecip = channel.unary_unary(
                '/WeatherHistory/GetPrecip',
                request_serializer=weather__pb2.Precip.SerializeToString,
                response_deserializer=weather__pb2.GetPrecipReturn.FromString,
                _registered_method=True)


class WeatherHistoryServicer(object):
    """python -m grpc_tools.protoc weather.proto --proto_path=. --python_out=. --grpc_python_out=. 

    """

    def GetSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrecipAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrecip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeatherHistoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSummary,
                    request_deserializer=weather__pb2.Summary.FromString,
                    response_serializer=weather__pb2.SummaryReturn.SerializeToString,
            ),
            'PrecipAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.PrecipAnalysis,
                    request_deserializer=weather__pb2.AnalysisSummary.FromString,
                    response_serializer=weather__pb2.AnalysisReturn.SerializeToString,
            ),
            'GetPrecip': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrecip,
                    request_deserializer=weather__pb2.Precip.FromString,
                    response_serializer=weather__pb2.GetPrecipReturn.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WeatherHistory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('WeatherHistory', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WeatherHistory(object):
    """python -m grpc_tools.protoc weather.proto --proto_path=. --python_out=. --grpc_python_out=. 

    """

    @staticmethod
    def GetSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WeatherHistory/GetSummary',
            weather__pb2.Summary.SerializeToString,
            weather__pb2.SummaryReturn.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrecipAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WeatherHistory/PrecipAnalysis',
            weather__pb2.AnalysisSummary.SerializeToString,
            weather__pb2.AnalysisReturn.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrecip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WeatherHistory/GetPrecip',
            weather__pb2.Precip.SerializeToString,
            weather__pb2.GetPrecipReturn.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
